Repository nikhil-RGB/flutter_automata, pull requests merged in 2023-03, with the labels that each got.

#6 Adding Core functionalities
  lib/CellButton.dart
  lib/CellGrid.dart
  lib/main.dart
  lib/models/Cell.dart
  lib/models/testing.dart
  lib/pages/AutomatonPage.dart
  lib/pages/InitializationPage.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#7 Adding functionalities and UI components
  google_fonts/SourceCodePro-Italic-VariableFont_wght.ttf
  google_fonts/SourceCodePro-VariableFont_wght.ttf
  lib/CellGrid.dart
  lib/main.dart
  lib/models/Cell.dart
  lib/pages/AutomatonPage.dart
  lib/pages/InitializationPage.dart
  lib/pages/WelcomePage.dart
  lib/util/DialogManager.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#8 Updating design file
  Flutter_Automata-final.fig
Labels: enhancement

#11 Fixing RenderOverflow in Automaton Page
  lib/pages/AutomatonPage.dart
Labels: bug

#12 Adding Beta Symmetric Key gen feature
  lib/pages/AutomatonPage.dart
  lib/pages/EncrypterPage.dart
  lib/pages/InitializationPage.dart
Labels: enhancement
